---

image: quay.io/roboll/helmfile:helm3-v0.140.0

stages:
  - test
  - deploy
  - e2e

.lint:
  variables:
    ENVIRONMENT: ""
    NAMESPACE: k4r-dev
  script:
    - helmfile -e "$ENVIRONMENT" --namespace "$NAMESPACE" lint
  interruptible: true
  only:
    - branches
    - merge_requests

lint-microk8s:
  stage: test
  when: manual
  extends: .lint
  variables:
    ENVIRONMENT: microk8s

lint-k4r-sandbox:
  stage: test
  extends: .lint
  variables:
    ENVIRONMENT: k4r.sandbox

lint-k4r-dev:
  stage: test
  extends: .lint
  variables:
    ENVIRONMENT: k4r.dev

lint-k4r-test:
  stage: test
  extends: .lint
  variables:
    ENVIRONMENT: k4r.test


.deploy:
  stage: deploy
  variables:
    ENVIRONMENT: ""
    CONTEXT: ""
    NAMESPACE: ""
  before_script:
    - kubectl config use-context $CONTEXT
  script:
    - helmfile -e "$ENVIRONMENT" --namespace "$NAMESPACE" sync
  interruptible: true

deploy-sandbox:
  extends: .deploy
  environment:
    name: sandbox
  variables:
    ENVIRONMENT: k4r.sandbox
    CONTEXT: k4r-sandbox-cluster
    NAMESPACE: k4r-sandbox
  only:
    refs:
      - main
      - merge_requests
  when: manual

deploy-test:
  extends: .deploy
  environment:
    name: test
  variables:
    ENVIRONMENT: k4r.test
    CONTEXT: k4r-test-cluster
    NAMESPACE: k4r-test
  only:
    refs:
      - main
      - merge_requests
  when: manual

deploy-dev:
  extends: .deploy
  environment:
    name: development
  variables:
    ENVIRONMENT: k4r.dev
    CONTEXT: k4r-platform-dev
    NAMESPACE: k4r-dev
  only:
    refs:
      - main

.end2end:
  stage: e2e
  image: gradle:alpine
  script:
    - echo $E2E_PROFILE
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/knowledge4retail/k4r-infrastructure-e2e.git
    - cd k4r-infrastructure-e2e
    - chmod +x gradlew
    - ./gradlew test
  interruptible: true
  allow_failure: true
  when: manual

e2e-sandbox:
  extends: .end2end
  environment:
    name: sandbox
  only:
    - merge_requests

e2e-dev:
  extends: .end2end
  environment:
    name: development
  only:
    refs:
      - main
