---
knowrob:
  externalApis:
    dt_url: "http://k4r-dt-api.k4r-sandbox.svc.cluster.local:8090/k4r/api/v0/"
    graphql_url: "http://k4r-dt-api.k4r-sandbox.svc.cluster.local:8090/k4r/graphql"
mongodb:
  username: "k4r"
  address: "mongodb"
  port: 27017
  uri: "mongodb"
  dbName: "roslog"

ingress:
  enabled: true
  issuerRef:
    name: letsencrypt
  hosts:
    - host: knowrob.sandbox.knowledge4retail.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - knowrob.sandbox.knowledge4retail.org
      secretName: knowrob.sandbox.knowledge4retail.org
oidcIngress:
  enabled: true
  issuerRef:
    name: letsencrypt
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2proxy.sandbox.knowledge4retail.org/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email, X-Auth-Request-Access-Token, Authorization"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # fix cors issues of ingress when using external auth service
      if ($request_method = OPTIONS) {
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 204;
      }
      more_set_headers "Access-Control-Allow-Credentials: true";
      more_set_headers "Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS";
      more_set_headers "Access-Control-Allow-Headers: Content-Type, Authorization";
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
      more_set_headers "Access-Control-Max-Age: 600";   
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"    
  hosts:
    - host: knowrob-oidc.sandbox.knowledge4retail.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - knowrob-oidc.sandbox.knowledge4retail.org
      secretName: knowrob-oidc.sandbox.knowledge4retail.org      

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "384Mi"
