---
data:
  ros_master_uri: http://robotics-planning.default.svc.cluster.local:11311

ingress:
  enabled: false
  tlsAuthEnabled: false
  annotations: {}
  issuerRef:
    name: letsencrypt
  hosts:
    - host: robotics-planning.default.knowledge4retail.org
  tls:
    - hosts:
      - robotics-planning.default.knowledge4retail.org
      secretName: robotics-planning.default.knowledge4retail.org

replicaCount: 1

image:
  repository: registry.gitlab.com/knowledge4retail/k4r-pa-projects/k4r-robotics-planning
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.308"  ## Must be replaced with a proper image tag, once available!

service:
  type: ClusterIP
  port: 9900
