---
app:
  env:
    erpAdapterUrl:
      url: http://erp-adapter.k4r-test.svc.cluster.local:8080/api/v0

ingress:
  issuerRef:
    name: letsencrypt
  enabled: true
  hosts:
    - host: sap-erp-adapter.test.knowledge4retail.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - sap-erp-adapter.test.knowledge4retail.org
      secretName: sap-erp-adapter.test.knowledge4retail.org

resources:
  limits:
    cpu: "300m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"
