---
app:
  env:
    erpAdapterUrl:
      url: http://erp-adapter:8080/api/v0

ingress:
  issuerRef:
    name: self-signed-issuer
  enabled: true
  hosts:
    - host: sap-erp-adapter.knowledge4retail.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - sap-erp-adapter.knowledge4retail.local
      secretName: sap-erp-adapter.knowledge4retail.local

tlsAuthDisabled: true
