---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "knowrob.fullname" . }}-entrypoint
  labels: 
    {{- include "knowrob.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  entrypoint.sh: |-
    #!/bin/bash
    source /home/ros/devel/setup.bash
    exec "$@"
