apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fridge.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fridge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fridge.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: {{ .Values.app.env.kafka.bootstrapServers.consumer }}
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: {{ .Values.app.env.kafka.bootstrapServers.producer }}
            - name: DT_API_URL
              value: {{ .Values.app.env.dtApiUrl.url }}
            - name: OPP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: opp-api-key
                  key: api-key
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
