---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
 # name must match the spec fields below, and be in the form: <plural>.<group>
 name: interfaces.knowledge4retail.org
spec:
 # group name to use for REST API: /apis/<group>/<version>
 group: knowledge4retail.org
 names:
   # plural name to be used in the URL: /apis/<group>/<version>/<plural>
   plural: interfaces
   # singular name to be used as an alias on the CLI and for display
   singular: interface
   # kind is normally the CamelCased singular type. Your resource manifests use this.
   kind: Interface
   shortNames:
   - k4ri
 # either Namespaced or Cluster
 scope: Namespaced
 versions:
   - name: v1alpha1
     # Each version can be enabled/disabled by Served flag.
     served: true
     # One and only one version must be marked as the storage version.
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           spec:
             type: object
             properties:
               serviceName:
                 type: string
               prettyName:
                 type: string
               description:
                 type: string				 
               version:
                 type: string
               interfaceType:
                 type: string
                 enum:
                   - WEBUI
                   - API
                   - ADMINISTRATION
               refFunctional:
                 type: string	               
               refDocs:
                 type: string	               
             required: ["serviceName", "prettyName", "description", "version", "interfaceType", "refFunctional", "refDocs"]
         required: ["spec"]
