apiVersion: knowledge4retail.org/v1alpha1
kind: Interface
metadata:
 name: robotics-web
spec:
 serviceName: {{ include "robotics-web.fullname" . }}
 prettyName: "Robotics Web" # manuell
 description: "Robot Planning Remote Control Application" # manuell
 version: {{ .Values.image.tag | default .Chart.AppVersion }}
 interfaceType: "WEBUI"
 refFunctional: "https://{{(index .Values.ingress.hosts 0).host | default "www.knowledge4retail.org"}}"
 refDocs: "https://gitlab.com/knowledge4retail/k4r-pa-projects/k4r-robotics-web"