apiVersion: knowledge4retail.org/v1alpha1
kind: Interface
metadata:
 name: k4r-distance-matrix-api
spec:
 serviceName: {{ include "k4r-distance-matrix-api.fullname" . }}
 prettyName: "Distance Matrix API" # manuell
 description: "OpenAPI Interface to the Distance Matrix Calculation" # manuell
 version: {{ .Values.image.tag | default .Chart.AppVersion }}
 interfaceType: "API"
 refFunctional: "https://{{(index .Values.ingress.hosts 0).host | default "www.knowledge4retail.org"}}/distancematrixapi/swagger-ui.html"
 refDocs: "https://www.knowledge4retail.org/docs/distance-matrix"