---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filipla.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filipla.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "filipla.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "filipla.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: filipla-planogram-web-config
          configMap:
            name: {{ include "filipla.fullname" . }}-web-config
      containers:
        - name: filipla-planogram-web
          image: "{{ .Values.components.web.image.repository }}:{{ .Values.components.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.components.web.image.pullPolicy }}
          volumeMounts:
          - name: filipla-planogram-web-config
            mountPath: /usr/share/nginx/html/assets/config.json
            subPath: FILIPLA_PLANOGRAM_WEB_CONFIG
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
      {{- toYaml .Values.components.web.resources | nindent 12 }}
          env:
          - name: RESTART_TRIGGER
            value: {{ .Values.components.web.restartTrigger | quote }}
