apiVersion: v1
kind: Service
metadata:
  name: {{ include "filipla.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.components.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.components.web.service.port }}
      targetPort: http
  selector:
    {{- include "filipla.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
