---
data:
  ros_master_uri: http://robotics-planning.k4r-test.svc.cluster.local:11311

ingress:
  enabled: true
  issuerRef:
    name: letsencrypt
  hosts:
    - host: robotics-web.test.knowledge4retail.org
  tls:
    - hosts:
      - robotics-web.test.knowledge4retail.org
      secretName: robotics-web.test.knowledge4retail.org

resources:
  limits:
    cpu: "300m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "128Mi"
