---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hetida.fullname" . }}-runtime
  labels:
    {{- include "hetida.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.storageClass }}
