apiVersion: v1
kind: Service
metadata:
  name: {{ include "hetida.fullname" . }}-runtime
  labels:
    {{- include "hetida.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.components.runtime.service.type }}
  ports:
    - name: http
      port: {{ .Values.components.runtime.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "hetida.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: runtime
