---
app:
  env:
    postgres:
      url: jdbc:postgresql://postgresql.k4r-test.svc.cluster.local:5432/k4r?currentSchema=dt_v1 # Override k4r-dev with your namespace
      user: k4r
    kafka:
      bootstrapServers:
        consumer: kafka:9092
        producer: kafka:9092
    blobstorage:
      container: k4r-device-images

# if needed so set storage class
storageClass: azurefile-csi

ingress:
  enabled: true
  issuerRef:
    name: letsencrypt
  hosts:
    - host: dt-api.test.knowledge4retail.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dt-api.test.knowledge4retail.org
      secretName: dt-api.test.knowledge4retail.org

oidcIngress:
  enabled: true
  issuerRef:
    name: letsencrypt
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2proxy.test.knowledge4retail.org/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email, X-Auth-Request-Access-Token, Authorization"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # fix cors issues of ingress when using external auth service
      if ($request_method = OPTIONS) {
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 204;
      }
      more_set_headers "Access-Control-Allow-Credentials: true";
      more_set_headers "Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS";
      more_set_headers "Access-Control-Allow-Headers: Content-Type, Authorization";
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
      more_set_headers "Access-Control-Max-Age: 600";   
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"    
  hosts:
    - host: dt-api-oidc.test.knowledge4retail.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dt-api-oidc.test.knowledge4retail.org
      secretName: dt-api-oidc.test.knowledge4retail.org

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus-monitoring
