apiVersion: knowledge4retail.org/v1alpha1
kind: Interface
metadata:
 name: erp-adapter
spec:
 serviceName: {{ include "erp-adapter.fullname" . }}
 prettyName: "ERP-Adapter Rest"
 description: "OpenAPI Interface to the Generic ERP-Adapter" 
 version: {{ .Values.image.tag | default .Chart.AppVersion }}
 interfaceType: "API"
 refFunctional: "https://{{(index .Values.ingress.hosts 0).host | default "www.knowledge4retail.org"}}/swagger-ui/index.html"
 refDocs: "https://www.knowledge4retail.org/docs/erp-adapter"