apiVersion: v1
kind: Service
metadata:
  name: {{ include "erp-adapter.fullname" . }}
  labels: {{- include "erp-adapter.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "erp-adapter.selectorLabels" . | nindent 4 }}
