---
app:
  DT_API_GRAPHQL_ENDPOINT: "https://dt-api-oidc.test.knowledge4retail.org/k4r/graphql"
  BACKGROUND_COLOR: "#16161d"
  OFFSET_TO_BOTTOM_LEFT: true

ingress:
  enabled: true
  issuerRef:
    name: letsencrypt
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2proxy.test.knowledge4retail.org/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2proxy.test.knowledge4retail.org/oauth2/start?rd=$scheme://$best_http_host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email, X-Auth-Request-Access-Token, Authorization"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  hosts:
    - host: storeviz.test.knowledge4retail.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - storeviz.test.knowledge4retail.org
      secretName: storeviz.test.knowledge4retail.org

