apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storeviz.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "storeviz.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "storeviz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "storeviz.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: storeviz-config
          configMap:
            name: storeviz-config      
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}    
          volumeMounts:
          - name: storeviz-config
            mountPath: /home/node/app/client/config/config.json
            subPath: STOREVIZ_CONFIG    
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health.html
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health.html
              port: http
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
