apiVersion: knowledge4retail.org/v1alpha1
kind: Interface
metadata:
 name: storeviz
spec:
 serviceName: {{ include "storeviz.fullname" . }}
 prettyName: "Store Visualization"
 description: "Interactive 3D representations of K4R Digital Twins"
 version: {{ .Values.image.tag | default .Chart.AppVersion }}
 interfaceType: "WEBUI"
 refFunctional: "https://{{(index .Values.ingress.hosts 0).host | default "www.knowledge4retail.org"}}"
 refDocs: "https://www.knowledge4retail.org/docs/storeviz"