---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
  namespace: {{ .Release.Namespace }}
  labels: {{- include "security.labels" . | nindent 4 }}
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  namespace: {{ .Release.Namespace }}
  labels: {{- include "security.labels" . | nindent 4 }}
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Egress
