# based on https://www.civo.com/learn/using-websockets-with-ingress-controller
# and hetida/templates/backend
apiVersion: v1
kind: Service
metadata:
  name: {{ include "robotics-planning.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "robotics-planning.selectorLabels" . | nindent 4 }}
  ports:
    - name: websocket
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: websocket
    - name: roscore
      protocol: TCP
      port: 11311
