---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filipla.fullname" . }}-backend-config
  namespace: {{ .Release.Namespace }}
data:
  FILIPLA_PLANOGRAM_BACKEND_CONFIG: |-
    {
        "planogram_workflow_execution_endpoint" : "https://hetida-backend/api/workflows/aeba5739-2c47-4d01-9aa0-69b0b4c49768/execute"
    }
