apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.components.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.components.backend.service.port }}
      targetPort: http ## the same target port in deployment
  selector:
    {{- include "filipla.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
