apiVersion: v1
kind: Service
metadata:
  name: {{ include "k4r-dt-api.fullname" . }}
  labels: {{- include "k4r-dt-api.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "k4r-dt-api.selectorLabels" . | nindent 4 }}
